language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

# also test against HHVM, but require "trusty" and ignore errors
matrix:
  include:
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - composer install
  
script:
  - vendor/bin/phpunit --coverage-text
